# Generated by Django 3.2.2 on 2021-05-10 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('step', models.CharField(choices=[('M', 'Materials'), ('T', 'Test'), ('R', 'Ready to Play')], default='M', max_length=1, verbose_name='Steps')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name', max_length=100)),
                ('description', models.TextField(help_text='Enter a description of the game', max_length=250)),
                ('instructions', models.TextField(default='1.            \n2.                 \n3.                 \n   ', help_text='Enter your instructions', max_length=250)),
                ('materials', models.CharField(help_text='Enter the materials you will need', max_length=100)),
                ('number', models.IntegerField(default=5, help_text='Enter the number of people who can play')),
                ('event', models.ManyToManyField(to='main_app.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Party Date')),
                ('name', models.CharField(max_length=150, verbose_name='Party Name')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
