# Generated by Django 3.2.2 on 2021-05-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='step',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2021-03-04', verbose_name='Date'),
            preserve_default=False,
        ),
    ]
