# Generated by Django 3.2.2 on 2021-05-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_planning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='meal',
            new_name='phase',
        ),
    ]
