# Generated by Django 3.2.2 on 2021-05-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210510_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='event',
            new_name='events',
        ),
    ]
