# Generated by Django 3.2.2 on 2021-05-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_event_game_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(default='1. ', help_text='Enter your instructions', max_length=250),
        ),
    ]
