# Generated by Django 3.2.2 on 2021-05-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_meal_planning_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.TextField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateField(verbose_name='complete date'),
        ),
    ]
