# Generated by Django 3.2.2 on 2021-05-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210507_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='materials',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
