# Generated by Django 3.2.2 on 2021-05-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_game_instructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Plan',
        ),
        migrations.RemoveField(
            model_name='game',
            name='events',
        ),
        migrations.AddField(
            model_name='game',
            name='plans',
            field=models.ManyToManyField(to='main_app.Plan'),
        ),
    ]
