# Generated by Django 3.2.2 on 2021-05-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210510_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.plan'),
            preserve_default=False,
        ),
    ]
