# Generated by Django 3.2.2 on 2021-05-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_game_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='complete date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='planning',
            options={'ordering': ['-date']},
        ),
    ]
