# Generated by Django 3.2.2 on 2021-05-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_game_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='events',
            field=models.ManyToManyField(to='main_app.Event'),
        ),
    ]
