# Generated by Django 3.2.2 on 2021-05-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_photo_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date',
        ),
        migrations.AddField(
            model_name='plan',
            name='difficulty',
            field=models.CharField(default='easy', max_length=150),
            preserve_default=False,
        ),
    ]
