# Generated by Django 3.2.2 on 2021-05-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210510_2327'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='plan',
    #         name='difficulty',
    #         field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1),
    #     ),
    # ]
