# Generated by Django 3.2.2 on 2021-05-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_plan_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='difficulty',
            field=models.CharField(max_length=150),
        ),
    ]
