# Generated by Django 3.2.2 on 2021-05-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210510_0137'),
        ('main_app', '0009_photo'),
    ]

    operations = [
    ]
