# Generated by Django 3.2.2 on 2021-05-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_plan_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='emoji',
            field=models.CharField(choices=[('A', '🍬'), ('Y', '🧶'), ('M', '🧵'), ('H', '✂️'), ('C', '🖍️'), ('S', '🧷'), ('P', '\U0001fa85'), ('B', '🎂'), ('T', '🎊')], default='A', max_length=1),
        ),
    ]
