# Generated by Django 3.2.2 on 2021-05-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='credit',
            field=models.CharField(max_length=50),
        ),
    ]
