# Generated by Django 3.2.2 on 2021-05-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
