# Generated by Django 3.2.2 on 2021-05-10 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_remove_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(related_name='game_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
