# Generated by Django 3.2.2 on 2021-05-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='credit',
        ),
    ]
