# Generated by Django 3.2.2 on 2021-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_game_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(default='1.', max_length=350),
        ),
        migrations.AlterField(
            model_name='game',
            name='materials',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(default=5),
        ),
    ]
