# Generated by Django 3.2.2 on 2021-05-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_game_credit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planning',
            new_name='Party',
        ),
    ]
