# Generated by Django 3.2.2 on 2021-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_planning_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(default='1.2.3.', max_length=250),
        ),
    ]
