# Generated by Django 3.2.2 on 2021-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210513_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='instructions',
        ),
        migrations.AddField(
            model_name='game',
            name='instructions1',
            field=models.TextField(default='1.', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='instructions2',
            field=models.TextField(default='2.', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='instructions3',
            field=models.TextField(default='3.', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='instructions4',
            field=models.TextField(default='4.', max_length=50),
        ),
    ]
