# Generated by Django 3.2.2 on 2021-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20210513_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='instructions1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='instructions2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='instructions3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='instructions4',
        ),
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.TextField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
