# Generated by Django 3.2.2 on 2021-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_game_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='phase',
            field=models.CharField(max_length=150),
        ),
    ]
