# Generated by Django 3.2.2 on 2021-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_game_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(default='\n   1.            \n   2.                 \n   3.                 \n   ', max_length=250),
        ),
    ]
