# Generated by Django 3.2.2 on 2021-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_party_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(help_text='</br>', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(help_text='</br>', max_length=350),
        ),
        migrations.AlterField(
            model_name='game',
            name='materials',
            field=models.CharField(help_text='</br>', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(help_text='</br>', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='where',
            field=models.CharField(choices=[('O', 'Outdoors'), ('I', 'Indoors'), ('B', 'Both'), ('V', 'Virtual')], default='O', help_text='</br>', max_length=1),
        ),
    ]
