# Generated by Django 3.2.2 on 2021-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_game_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(help_text='Enter a description of the game', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(default='1.            \n2.                 \n3.                 \n   ', help_text='Enter your instructions', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='materials',
            field=models.CharField(help_text='Enter the materials you will need', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(default=5, help_text='Enter the number of people who can play'),
        ),
    ]
