# Generated by Django 3.2.2 on 2021-05-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_merge_0009_auto_20210509_2348_0029_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
