# Generated by Django 3.2.2 on 2021-05-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='phase',
            new_name='name',
        ),
    ]
