# Generated by Django 3.2.2 on 2021-05-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_rename_phase_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='date',
            field=models.DateField(verbose_name='pick a date'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Party Name'),
        ),
    ]
